### ISSUE TITLE
Make cgr-loader and friends use settings from cgrates.json

### ISSUE THREAD

**Issue by sebastic** [cgrates/cgrates#964]
`cgr-loader` and other commands don't use settings from the CGRateS configuration file (`cgrates.json`) and require the user to specify the options on the commandline.

These commands should support loading the settings from `cgrates.json` like `cgr-engine`.

**Comment by danbogos** [comment]
Hi @sebastic 

Please test the cgr-loader since it should now work with config options.

DanB

**Comment by sebastic** [comment]
CC: @deanone-noc

**Comment by sebastic** [comment]
Why is a separate config file used instead of reusing `cgrates.json` (as the default)?
```
# cgr-loader --help 2>&1 | head
Usage of cgr-loader:
  -cdrstats string
        CDRStats service to contact for data reloads, empty to disable automatic data reloads
  -config_path string
        Full path towards configuration file (default "/etc/cgrates/cgr-loader.cfg")
  -datadb_host string
        The DataDb host to connect to.
  -datadb_name string
        The name/number of the DataDb to connect to.
  -datadb_passwd string
```

It also looks like the hardcoded default values aren't used like `cgr-engine` does:
```
# cgr-loader -config_path /etc/cgrates/cgrates-test-import.json -dry_run -verbose
Error loading config file Could not open the configuration file: could not parse line: {Config before changing DataDBType: null 
 
Config after changing DataDBType: null 
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb94bf6]

goroutine 1 [running]:
main.main()
        /usr/local/gopath/src/github.com/cgrates/cgrates/src/github.com/cgrates/cgrates/cmd/cgr-loader/cgr-loader.go:185 +0x3936
```
This config file in question is identical to the `cgrates.json` used by `cgr-engine` except for the `db_name` of the `data_db` & `stor_db`.

**Comment by danbogos** [comment]
hi @sebastic 

We have decided to go with another file for clearness (isolating parameters for each binary). Since for loader we don't need objects encapsulation, we have used .cfg (.ini style) instead of json, in this way being possible to keep all configs in the same folder by default (engine will only read .json files).

DanB

**Comment by sebastic** [comment]
So we still need to duplicate the database settings. instead of commandline arguments we can now put them in a separate config file. That's better than having to specify the commandline arguments every time, but it still requires duplicating settings that are already defined in {{cgrates.json}} and hence doesn't fix this issue.

**Comment by danbogos** [comment]
If by duplicating means copy/paste from one file into another, yes, that is true, you still need to duplicate. However I see it as defining once and re-using on each import, so it should in theory fix at least something.

DanB

**Comment by danbogos** [comment]
@sebastic 

FYI, reviewed it again internally and will go in the end with your suggestion, from cgrates.json. The idea is that the common settings will be taken from old config and particular settings for cgr-loader will go into it's own section, so there will be no conflicts with using the same folder.

Will update ticket as soon as you are able to test.

Thanks,
DanB

**Comment by TeoV** [comment]
Hi sebastic,
This feature is available in master.
Please come back if any issues.

Thanks,
TeoV

**Comment by esfandiaryfard** [comment]
I followed the answers but I couldn't solve my problem, I have configured cgrates on /etc/cgrates/cgrates.json but it seems cgr-* does not read from this file
